name: New version check

on:
  schedule:
    # run every hour (at minute 57)
    - cron: '57 * * * *'
  workflow_dispatch:

jobs:
  check-new-beta:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: beta
      - name: Extract current beta version
        id: extract-current-version-beta
        run: |
          version=$(sed -n 's/^version: "\(.*\)"$/\1/p' snapcraft.yaml)
          echo "::set-output name=version::$version"
      - name: install python deps
        run: sudo apt update && sudo apt install python3-lxml python3-packaging
      - name: Fetch new version
        id: fetch-new-version-beta
        run: |
          version=$(./.github/scripts/check-new-version.py beta ${{ steps.extract-current-version-beta.outputs.version }})
          echo "::set-output name=version::$version"
      - name: update snapcraft.yaml with the new version
        if: steps.fetch-new-version-beta.outputs.version
        run: |
          version=${{ steps.fetch-new-version-beta.outputs.version }}
          sed -i "s/^version: \"\(.*\)\"$/version: \"$version\"/" snapcraft.yaml
          git add snapcraft.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Bump version to the latest beta ($version)."
          git push
      - uses: snapcore/action-build@v1
        id: build-new-snap-beta
        if: steps.fetch-new-version-beta.outputs.version
      - uses: snapcore/action-publish@v1
        if: steps.fetch-new-version-beta.outputs.version
        with:
          store_login: ${{ secrets.SNAPSTORE_LOGIN }}
          snap: ${{ steps.build-new-snap-beta.outputs.snap }}
          release: beta
