name: Nightly snap build

on:
  schedule:
    # Run every 12 hours (Nightly builds start at 10:00 and 22:00 UTC,
    # and usually builds are available one hour or two later). Give some room
    # and assume new builds will be available 3 hours after they start.
    - cron: '0 1,13 * * *'
  # Allow running manually, for testing purposes.
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  nightly-snap:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: nightly
      - name: Free up some disk space
        run: sudo rm -rf /usr/share/dotnet /opt/ghc "$AGENT_TOOLSDIRECTORY"
      - name: Extract current version
        id: extract-current-version
        run: ./.github/scripts/extract-current-version.sh
      - name: Set Mozilla debug symbols token
        id: moz-dbgsymup-token
        env:
          MOZ_DBGSYMUP_TOKEN: ${{ secrets.MOZ_DBGSYMUP_TOKEN }}
        run: ./.github/scripts/moz-dbgsymup-token.sh
      - uses: snapcore/action-build@v1
        id: build-new-snap-nightly
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPSTORE_LOGIN }}
        with:
          snap: ${{ steps.build-new-snap-nightly.outputs.snap }}
          release: edge
      - name: Install the marionette driver
        run: |
          sudo apt update && sudo apt install python3-pip
          pip3 install marionette_driver
      - name: Create missing user runtime directory
        run: |
          sudo mkdir -p /run/user/$UID
          sudo chown $USER /run/user/$UID
      - name: Install the snap from the store and run some basic tests
        run: |
          sudo snap install firefox --edge
          channel=$(snap info firefox | grep tracking: | cut -d: -f2 | xargs)
          [ $channel = "latest/edge" ]
          installed=$(snap info firefox | grep installed: | cut -d: -f2 | xargs | cut -d' ' -f1)
          [ $installed = ${{ env.current_version }} ]
          runtimeversion=$(snap run firefox --version)
          snap run firefox --headless --marionette &
          pid=$!
          ./.github/scripts/firefox-basic-tests.py $pid "$runtimeversion"
